name: sergioideando
favicon: null
layout_spectrum: 0.46823855955153704
typography_spectrum: 0.9981892516370863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01ccff'
    - '#00001e'
    - '#f7fcff'
    - '#b9908e'
    - '#90483c'
  brandStrength: 1
  lightness: 0.1551884284708649
  saturation: 0.34932775842025876
  rhythmicContrast: 0.8380260528065264
purpose: []
