name: sergioideando
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24289
title: Personal site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#309fa7'
    - '#000000'
    - '#ff0000'
    - '#00ffff'
    - '#ffff00'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
